name: Copy All Docker Image
on: 
  workflow_dispatch:
    inputs:
      source:
        description: '镜像源 (Registry)'     
        required: true
        default: 'docker.io'
      destination:
        description: '目标源 (Registry)'
        required: true
        default: 'registry.cn-chengdu.aliyuncs.com'
      source_repo:
        description: '仓库及标签 (格式 repo:tag)'
        required: true
        default: ''
      destination_repo:
        description: '目标仓库及标签 (格式 repo:tag)'
        required: true
        default: 'parent/'

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: linux/arm64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to source registry
      env:
        USERNAME: ${{ secrets.SOURCE_USERNAME }}
        PASSWORD: ${{ secrets.SOURCE_CREDENTIAL }}
      run: echo $PASSWORD | docker login ${{ github.event.inputs.source }} --username $USERNAME --password-stdin

    - name: Log in to destination registry
      env:
        USERNAME: ${{ secrets.DESTINATION_USERNAME }}
        PASSWORD: ${{ secrets.DESTINATION_CREDENTIAL }}
      run: echo $PASSWORD | docker login ${{ github.event.inputs.destination }} --username $USERNAME --password-stdin

    - name: Copy Docker Images
      uses: ikrong/docker-sync-action@main
      with:
        source: ${{ github.event.inputs.source }}
        source-credential: ${{ secrets.SOURCE_CREDENTIAL }}
        destination: ${{ github.event.inputs.destination }}
        destination-credential: ${{ secrets.DESTINATION_CREDENTIAL }}
        copy: "${{ github.event.inputs.source_repo }} ${{ github.event.inputs.destination_repo }}"
