name: Build and Push Docker Images
on: 
  workflow_dispatch:
    inputs:
      source:
        description: '镜像源 (Registry)'     
        required: true
        default: 'docker.io'
      destination:
        description: '目标源 (Registry)'
        required: true
        default: 'registry.cn-chengdu.aliyuncs.com'
      source_repo:
        description: '仓库及标签 (格式 repo:tag)'
        required: true
        default: ''
      destination_repo:
        description: '目标仓库及标签 (格式 repo:tag)'
        required: true
        default: 'parent/'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # 检出代码仓库

    - name: Build and push Docker images
      uses: docker/build-push-action@v6.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub 用户名或其他 Docker 注册表的用户名
        password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub 密码或其他 Docker 注册表的密码
        repository: yourusername/yourimage  # 要推送的 Docker 镜像仓库路径，可以是带用户名的完整路径
        tags: |
          latest  # 镜像的标签，可以是多个，使用换行符分隔

    - name: Clean up
      run: |
        docker image prune -f  # 清理未使用的镜像，可选步骤
