name: Copy All Docker Image
on: 
  workflow_dispatch:
    inputs:
      source:
        description: '镜像源 (Registry)'     
        required: true
        default: 'docker.io'
      destination:
        description: '目标源 (Registry)'
        required: true
        default: 'registry.cn-chengdu.aliyuncs.com'
      source_repo:
        description: '仓库及标签 (格式 repo:tag)'
        required: true
        default: ''
      destination_repo:
        description: '目标仓库及标签 (格式 repo:tag)'
        required: true
        default: 'parent/'

jobs:
  pull_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to destination registry
      env:
        USERNAME: ${{ secrets.ALICLOUD_USERNAME }}
        PASSWORD: ${{ secrets.ALICLOUD_PASSWORD }}
      run: echo $PASSWORD | docker login ${{ github.event.inputs.destination }} --username $USERNAME --password-stdin

    - name: Pull Docker Images, Tag, and Push
      run: |
        images="${{ github.event.inputs.docker_images }}"
        destination="${{ github.event.inputs.destination }}"
        destination_repo="${{ github.event.inputs.destination_repo }}"
        IFS=',' read -r -a image_array <<< "$images"
        for image in "${image_array[@]}"; do
          docker pull "${image}" --platform "linux/arm64"
          image_name=$(echo "${image}" | awk -F':' '{print $1}')
          image_tag=$(echo "${image}" | awk -F':' '{print $2}')
          new_image="${destination}/${destination_repo}/${image_name}:${image_tag}"
          docker tag "${image}" "${new_image}"
          docker push "${new_image}"
        done

    - name: Clean up intermediate files
      run: |
        docker system prune -f
