on:
  workflow_dispatch:
    inputs:
      source:
        description: '镜像源 (Registry)'     
        required: false
        default: 'docker.io'
      destination:
        description: '目标源 (Registry)'
        required: true
        default: 'registry.cn-chengdu.aliyuncs.com'
      source_repo:
        description: '仓库及标签 (格式 repo:tag)'
        required: true
        default: ''
      destination_repo:
        description: '目标仓库及标签 (格式 repo:tag)'
        required: true
        default: 'parent/'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Pull and push multi-platform images
        run: |
          docker buildx create --use
          docker pull ${{ github.event.inputs.source_repo }} 
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ github.event.inputs.destination }}/${{ github.event.inputs.destination_repo }} --push ${{ github.event.inputs.source }}/${{ github.event.inputs.source_repo }}
