on:
  workflow_dispatch:
    inputs:
      source:
        description: '镜像源 (Registry)'     
        required: false
        default: 'docker.io'
      destination:
        description: '目标源 (Registry)'
        required: true
        default: 'registry.cn-chengdu.aliyuncs.com'
      source_repo:
        description: '仓库及标签 (格式 repo:tag)'
        required: true
        default: ''
      destination_repo:
        description: '目标仓库及标签 (格式 repo:tag)'
        required: true
        default: 'parent/'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Pull and push multi-platform images
        run: |
          docker buildx create --use
          docker pull ${{ github.event.inputs.source_repo }} --platform linux/amd6
          docker tag ${{ github.event.inputs.source_repo }} registry.cn-chengdu.aliyuncs.com/my-aliyun-repo/mysql:latest
          
      - name: Login to Alibaba Cloud Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-chengdu.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_TOKEN }}
      
      - name: Push image to Alibaba Cloud Container Registry
        run: |
          docker push registry.cn-chengdu.aliyuncs.com/${{ github.event.inputs.destination_repo }}
